### ISSUE TITLE
MT workflow not compatible with genmod scoring 

### ISSUE THREAD

**Issue by jemten** [nf-core/raredisease#370]
### Description of the bug

Email from @fa2k suggests that the MT workflow currently isn't compatible with genmod scoring. Resulting in this error. 
```
[2023-06-23 12:54:34,507] DEBUG   : genmod.commands.score_variants: Adding category score 0 to rank_score
[2023-06-23 12:54:34,507] DEBUG   : genmod.commands.score_variants: Updating rank score to 4
[2023-06-23 12:54:34,507] DEBUG   : genmod.score_variants.score_variant: Checking scores for category splicing
[2023-06-23 12:54:34,507] DEBUG   : genmod.score_variants.score_variant: Checking scores for plugin maxentscan_naitive_alt
Traceback (most recent call last):
  File "/usr/local/bin/genmod", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/genmod/commands/score_variants.py", line 173, in score
    category_score = get_category_score(
  File "/usr/local/lib/python3.9/site-packages/genmod/score_variants/score_variant.py", line 55, in get_category_score
    category_scores.append(get_plugin_score(
  File "/usr/local/lib/python3.9/site-packages/genmod/score_variants/score_variant.py", line 27, in get_plugin_score
    value = plugin.get_value(variant_dict=variant, csq_format=csq_format)
  File "/usr/local/lib/python3.9/site-packages/extract_vcf/plugin.py", line 349, in get_value
    for value in self.get_entry(
  File "/usr/local/lib/python3.9/site-packages/extract_vcf/plugin.py", line 136, in get_entry
    entry += split_strings(csq_entry.split('|')[csq_column], self.separators)
IndexError: list index out of range
```
Workaround for now is to disable the MT workflow if you want scoring on the MT.

**Comment by fa2k** [comment]
This seems to be fixed in 1.1.1. There's no crash when running with MT-analysis. I had a problem with the VEP configuration, which was different for ENSEMBLEVEP_SNV & ENSEMBLVEP_MT. Even with this problem there was no crash with 1.1.1, but after fixing it, it also has the same number of fields in CSQ. It's possible that the problem was never in the pipeline, and only in my configuration.

**Comment by jemten** [comment]
Interesting, we will try to run the pipe on our end and check.

**Comment by ramprasadn** [comment]
MT workflow has been restructured in https://github.com/nf-core/raredisease/pull/419. So I am closing this issue.
