### ISSUE TITLE
manta path error

### ISSUE THREAD

**Issue by egenomics** [nf-core/raredisease#480]
### Description of the bug

Manta fails with a path error:
```
  error [java.lang.InterruptedException]: java.lang.InterruptedException
Jan-16 03:00:07.184 [Actor Thread 16] ERROR nextflow.processor.TaskProcessor - Error executing process > 'NFCORE_RAREDISEASE:RAREDISEASE:CALL_STRUCTURAL_VARIANTS:CALL_SV_MANTA:MANTA (1)'

Caused by:
  Path value cannot be null
```

### Command used and terminal output

```console
nextflow run /playground/nf-core-raredisease_1.1.1/1_1_1/      -profile singularity     --input /playground/dataset_cnvs/samplesheet.csv     --skip_snv_annotation     --skip_sv_annotation     --skip_cnv_calling     --outdir /playground/dataset_cnvs/results     --intervals_wgs /playground/dataset_cnvs/Illumina-truseq-rapid-exome_v1.2_hg38_target_orig.interval_list     --intervals_y /playground/dataset_cnvs/Illumina-truseq-rapid-exome_v1.2_hg38_target_orig.interval_list     --skip_mt_analysis     --skip_vep_filter     --target_bed /playground/dataset_cnvs/Illumina-truseq-rapid-exome_v1.2_hg38_target_orig.bed     --variant_catalog /playground/dataset_cnvs/variant_catalog.json
```

### Relevant files

[nextflow.log](https://github.com/nf-core/raredisease/files/13947323/nextflow.log)

### System information

nextflow version 23.10.0.5889
Workstation
local (singularity)
Ubuntu 22.04.03 LTS
raredisease 1.1.1

**Comment by egenomics** [comment]
-resume [name_run] also doesn't seem to work, as it does not recover the bwa-mem2 or fastqc processes, that were finished.

**Comment by egenomics** [comment]
yes, they are exomes. I managed to have -resume working but it gets the same path value cannot be null error in manta :(

**Comment by egenomics** [comment]
Any idea where the error might be?

**Comment by jemten** [comment]
Hmm something seems to be off when combining the channels for going from a sample to case. From looking at the logs it looks like the samples aren't related in any way. Is that correct?

**Comment by egenomics** [comment]
Yes, in theory they are not related. Should I process every "case" separately in a difference nextflow run - samplesheet instance?

**Comment by jemten** [comment]
I think it's worth trying to do that while we are trying to nail down why the first setup doesn't work. Also, if possible, could you share your samplesheet?

**Comment by jemten** [comment]
Try to start one and see if the error persists. The pipeline should be compatible with your setup, and otherwise we'll try to fix it. We are working to get a new release out in a couple of week so it would be good to get a grip on the issue.

**Comment by egenomics** [comment]
Hi,
I  get a different error when processing samples one by one (error at the end).

The command is this one
```
nextflow run /playground/nf-core-raredisease_1.1.1/1_1_1/ -profile singularity \
--input /playground/dataset_cnvs/samplesheets_raredisease/samplesheet_$sample.csv --skip_snv_annotation --skip_sv_annotation --skip_cnv_calling \
--outdir /playground/dataset_cnvs/results/$sample --intervals_wgs /playground/dataset_cnvs/Illumina-truseq-rapid-exome_v1.2_hg38_target_orig.interval_list \
 --intervals_y /playground/dataset_cnvs/Illumina-truseq-rapid-exome_v1.2_hg38_target_orig.interval_list --skip_mt_analysis --skip_vep_filter \
 --target_bed /playground/dataset_cnvs/Illumina-truseq-rapid-exome_v1.2_hg38_target_orig.bed \
 --variant_catalog /playground/dataset_cnvs/variant_catalog.json \
 --analysis_type wes

```
```

ERROR ~ Error executing process > 'NFCORE_RAREDISEASE:RAREDISEASE:PREPARE_REFERENCES:GATK_BILT (playground)'

Caused by:
  Process `NFCORE_RAREDISEASE:RAREDISEASE:PREPARE_REFERENCES:GATK_BILT (playground)` terminated with an error exit status (3)

Command executed:

  gatk --java-options "-Xmx24576M" BedToIntervalList \
      --INPUT Illumina-truseq-rapid-exome_v1.2_hg38_target_orig.bed \
      --OUTPUT playground_target.interval_list \
      --SEQUENCE_DICTIONARY genome.dict \
      --TMP_DIR . \
  
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RAREDISEASE:RAREDISEASE:PREPARE_REFERENCES:GATK_BILT":
      gatk4: $(echo $(gatk --version 2>&1) | sed 's/^.*(GATK) v//; s/ .*$//')
  END_VERSIONS

Command exit status:
  3

Command output:
  (empty)

Command error:
  Using GATK jar /usr/local/share/gatk4-4.4.0.0-0/gatk-package-4.4.0.0-local.jar
  Running:
      java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx24576M -jar /usr/local/share/gatk4-4.4.0.0-0/gatk-package-4.4.0.0-local.jar BedToIntervalList --INPUT Illumina-truseq-rapid-exome_v1.2_hg38_target_orig.bed --OUTPUT playground_target.interval_list --SEQUENCE_DICTIONARY genome.dict --TMP_DIR .
  08:58:38.845 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/share/gatk4-4.4.0.0-0/gatk-package-4.4.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
  [Fri Jan 26 08:58:38 GMT 2024] BedToIntervalList --INPUT Illumina-truseq-rapid-exome_v1.2_hg38_target_orig.bed --SEQUENCE_DICTIONARY genome.dict --OUTPUT playground_target.interval_list --TMP_DIR . --SORT true --UNIQUE false --DROP_MISSING_CONTIGS false --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 2 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
  [Fri Jan 26 08:58:38 GMT 2024] Executing as jlvillanueva@HCP14035 on Linux 6.5.0-14-generic amd64; OpenJDK 64-Bit Server VM 17.0.3-internal+0-adhoc..src; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: Version:4.4.0.0
  [Fri Jan 26 08:58:39 GMT 2024] picard.util.BedToIntervalList done. Elapsed time: 0.00 minutes.
  Runtime.totalMemory()=285212672
  To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
  picard.PicardException: Start on sequence 'chr4' was past the end: 112788531 < 112904435
  	at picard.util.BedToIntervalList.doWork(BedToIntervalList.java:160)
  	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:289)
  	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:37)
  	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
  	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
  	at org.broadinstitute.hellbender.Main.main(Main.java:289)

Work dir:
  /playground/work/66/42850f2837916a14b7ce930937ae25

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details

```

**Comment by ramprasadn** [comment]
hmmm.. Would it be possible for you to share your bed file and your dictionary file?

**Comment by egenomics** [comment]
file:///playground/dataset_cnvs/Illumina-truseq-rapid-exome_v1.2_hg38_target_orig.tar.xz

**Comment by ramprasadn** [comment]
I will close this issue since there hasn't been any recent activity. Feel free to reopen it if you'd like to discuss it further.
